# Generated by Django 2.2.7 on 2019-11-19 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('occupation', models.CharField(max_length=40)),
                ('company_name', models.CharField(max_length=50)),
                ('is_recruiter', models.BooleanField()),
                ('gender', models.CharField(choices=[('MA', 'Male'), ('FE', 'Female'), ('OT', 'Other')], default='MA', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=50)),
                ('is_student', models.BooleanField()),
                ('experience', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('skills', models.TextField(null=True)),
                ('education', models.TextField()),
                ('certification', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
